global:
  scrape_interval: 2s
  evaluation_interval: 1s

rule_files:
  - alert.rules
  - recording.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - demo.robustperception.io:9090
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets:
        - demo.robustperception.io:9091
  - job_name: 'alertmanager'
    honor_labels: true
    static_configs:
      - targets:
        - demo.robustperception.io:9093
  - job_name: 'node'
    static_configs:
      - targets:
        - demo.robustperception.io:9100
  - job_name: 'localpushgateway'
    honor_labels: true
    static_configs:
      - targets:
        - 192.168.2.102:9091

